CI failed artifact upload: fix name
Error from https://github.com/related-sciences/ensembl-genes/runs/4931417284?check_suite_focus=true#step:6:12
> Error: Artifact name is not valid: failed_output/mus_musculus_core_105_39. Contains the following character:  Forward slash /
> Invalid characters include:  Double quote ", Colon :, Less than <, Greater than >, Vertical bar |, Asterisk *, Question mark ?, Carriage return \r, Line feed \n, Backslash \, Forward slash /
> These characters are not allowed in the artifact name due to limitations with certain file systems such as NTFS. To maintain file system agnostic behavior, these characters are intentionally not allowed to prevent potential problems with downloads on different file systems.

Switch to underscore in name.