fix empty pd.DataFrame error in alt_allele_df
resulted from the pandas upgrade in f00003c11972418be07e827d6746b22a6cb54059

IndexError: single positional indexer is out-of-bounds
https://github.com/related-sciences/ensembl-genes/runs/4930879765?check_suite_focus=true#step:5:75